apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: postgres
data:
  POSTGRES_DB: "postgres"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "password123#"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pgbouncer-config
  labels:
    app: pgbouncer
data:
  POSTGRESQL_HOST: "localhost"
  POSTGRESQL_DATABASE: "postgres"
  POSTGRESQL_USERNAME: "postgres"
  POSTGRESQL_PASSWORD: "password123#"
  PGBOUNCER_DATABASE: "postgres"
  PGBOUNCER_MAX_CLIENT_CONN: "200"
  PGBOUNCER_POOL_MODE: "transaction"
  PGBOUNCER_INIT_SLEEP_TIME: "10"
  PGBOUNCER_DEFAULT_POOL_SIZE: "20"
  PGBOUNCER_LOG_CONNECTIONS: "1"
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-pv-volume
  labels:
    type: local
    app: postgres
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/pg_data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pv-claim
  labels:
    app: postgres
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: itssoumen/postgresql-server
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb
        - name: pgbouncer
          image: bitnami/pgbouncer
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 6432
          envFrom:
            - configMapRef:
                name: pgbouncer-config
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: postgres-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-db
  labels:
    app: postgres
spec:
  type: LoadBalancer
  ports:
    - port: 6432
      name: pgbouncer_port
    - port: 5432
      name: postgresql_port
  selector:
    app: postgres
